/*
	-----------------------------------
	ARRAYS FOR GENRES / SEARCH TERMS	
	-----------------------------------
*/

var hiphop = [

"Alternative hip hop",
"Australian hip hop",
"Bongo Flava",
"British hip hop",
"Chap hop",
"Christian hip hop",
"Conscious hip hop",
"Country-rap",
"Crunk",
"Crunkcore",
"Cumbia rap",
"Drill",
"East Coast hip hop",
"Baltimore club",
"Brick City club",
"Hardcore hip hop",
"Mafioso rap",
"New Jersey hip hop",
"Electro music",
"Experimental hip hop",
"Freestyle rap",
"Gangsta rap",
"Ghetto house",
"Ghettotech",
"Golden age hip hop",
"Grime",
"Hardcore hip hop",
"Hip house",
"Hiplife",
"Hip pop",
"Igbo rap",
"Industrial hip hop",
"Instrumental hip hop",
"Jazz rap",
"Kwaito",
"Lyrical hip hop",
"Low Bap",
"Midwest hip hop",
"Chicago hip hop",
"Ghetto house",
"Detroit hip hop",
"Ghettotech",
"St. Louis hip hop",
"Twin Cities hip hop",
"Horrorcore",
"Merenrap",
"Motswako",
"Nerdcore",
"New jack swing",
"New school hip hop",
"Old school hip hop",
"Political hip hop",
"Ragga",
"Reggaeton",
"Rap opera",
"Rap rock",
"Rapcore",
"Rap metal",
"Reggae Español/Spanish Reggae",
"Southern hip hop",
"Atlanta hip hop",
"Snap music",
"Bounce music",
"Crunk",
"Houston hip hop",
"Chopped and screwed",
"Miami bass",
"Songo-salsa",
"Trap",
"Trip hop (or Bristol sound)",
"Turntablism",
"Underground hip hop",
"Urban Pasifika",
"West Coast hip hop",
"Chicano rap",
"G-funk",
"Hyphy",
"Jerkin"

];

var jazz = [

'Acid jazz',
'Afro-Cuban jazz',
'Asian American jazz',
'Avant-garde jazz',
'Bebop',
'Boogie-woogie',
'Bossa nova',
'British dance band',
'Cape jazz',
'Chamber jazz',
'Continental jazz',
'Cool jazz',
'Crossover jazz',
'Dixieland',
'Ethno jazz',
'European free jazz',
'Free funk',
'Free improvisation',
'Free jazz',
'Gypsy jazz',
'Hard bop',
'Jazz blues',
'Jazz-funk',
'Jazz fusion',
'Jazz rap',
'Jazz rock',
'Kansas City blues',
'Kansas City jazz',
'Latin jazz',
'Livetronica',
'M-Base',
'Mainstream jazz',
'Modal jazz',
'Neo-bop jazz',
'Neo-swing',
'Novelty ragtime',
'Nu jazz',
'Orchestral jazz',
'Post-bop',
'Punk jazz',
'Ragtime',
'Shibuya-kei',
'Ska jazz',
'Smooth jazz',
'Soul jazz',
'Stride jazz',
'Straight-ahead jazz',
'Swing',
'Third stream',
'Trad jazz',
'Vocal jazz',
'West Coast jazz'

];

var pop = [

'Adult contemporary',
'Arab pop',
'Baroque pop',
'Britpop',
'Bubblegum pop',
'Canción',
'Canzone',
'Chalga',
'Chanson',
'Christian pop',
'Classical crossover',
'Country pop',
'C-pop',
'Mandopop',
'Dance-pop',
'Disco polo',
'Electropop',
'Europop',
'Austropop',
'Eurobeat',
'French pop',
'Italo dance',
'Italo disco',
'Laïkó',
'Latin pop',
'Nederpop',
'Russian pop',
'Fado',
'Folk pop',
'Iranian pop',
'Indie pop',
'J-pop',
'Jangle pop',
'K-pop',
'Latin ballad',
'Louisiana swamp pop',
'Mexican pop',
'New Romanticism',
'Operatic pop',
'Pop rap',
'Pop rock',
'Power pop',
'Soft rock',
'Pop soul',
'Progressive pop',
'Psychedelic pop',
'Rebetiko',
'Schlager',
'Sophisti-pop',
'Space age pop',
'Sunshine pop',
'Surf pop',
'Synthpop',
'Teen pop',
'Traditional pop music',
'Turkish pop',
'Vispop',
'Wonky pop',
'Worldbeat'

];

var rock = [

'Neue Deutsche Härte',
'Alternative rock',
'Grunge',
'Post-grunge',
'Indie rock',
'Dunedin Sound',
'Post-punk revival',
'Industrial rock',
'Post-rock',
'Post-metal',
'Sadcore',
'Shoegaze',
'Slowcore',
'Art rock',
'Beat music',
'Chinese rock',
'Christian rock',
'Electronicore',
'Dark cabaret',
'Experimental rock',
'Electronic rock',
'Folk rock',
'Garage rock',
'Glam rock',
'Hard rock',
'Heavy metal',
'Alternative metal',
'Avant-garde metal',
'Black metal',
'Symphonic black metal',
'Viking metal',
'War metal',
'Christian metal',
'Death metal',
'Death n roll',
'Melodic death metal',
'Technical death metal',
'Goregrind',
'Doom metal',
'Death-doom',
'Drone metal',
'Folk metal',
'Celtic metal',
'Medieval metal',
'Pagan metal',
'Funk metal',
'Glam metal',
'Gothic metal',
'Grindcore',
'Industrial metal',
'Latin metal',
'Metalcore',
'Melodic metalcore',
'Deathcore',
'Mathcore',
'Neoclassical metal',
'Nu metal',
'Post-metal',
'Power metal',
'Progressive metal',
'Djent',
'Rap metal',
'Sludge metal',
'Speed metal',
'Symphonic metal',
'Thrash metal',
'Crossover thrash',
'Groove metal',
'Unblack metal',
'Jazz rock',
'Math rock',
'New wave',
'World fusion',
'Paisley Underground',
'Desert rock',
'Pop rock',
'Soft rock',
'Progressive rock',
'Canterbury scene',
'Krautrock',
'New prog',
'Rock in Opposition',
'Space rock',
'Psychedelic rock',
'Acid rock',
'Freakbeat',
'Neo-psychedelia',
'Raga rock',
'Punk rock',
'Anarcho punk',
'Crust punk',
'D-beat',
'Art punk',
'Christian punk',
'Deathrock',
'Digital hardcore',
'Folk punk',
'Celtic punk',
'Cowpunk',
'Gypsy punk',
'Garage punk',
'Grindcore',
'Crustgrind',
'Noisegrind',
'Hardcore punk',
'Post-hardcore',
'Emo',
'Screamo',
'Thrashcore',
'Crossover thrash',
'Powerviolence',
'Street punk',
'Horror punk',
'Pop punk',
'Psychobilly',
'Riot grrrl',
'Ska punk',
'Skate punk',
'Post-punk',
'Gothic rock',
'No wave',
'Noise rock',
'Rap rock',
'Rapcore',
'Rock and roll',
'Southern rock',
'Stoner rock',
'Sufi rock',
'Surf rock',
'Visual kei',
'Nagoya kei',
'Worldbeat'

];

var soul = [

'Contemporary R&B',
'Disco',
'Funk',
'Deep funk',
'Freestyle music',
'Go-go',
'Hip hop soul',
'P-Funk',
'Post-disco',
'Boogie',
'New jack swing',
'Rhythm and blues',
'Soul',
'Blue-eyed soul',
'Hip hop soul',
'Northern soul',
'Neo soul',
'Southern soul'

];

var latin = [

'Bachata',
'Banda',
'Bolero',
'Cumbia',
'Huayno',
'Chicha',
'Criolla',
'Flamenco',
'Mambo',
'Mariachi',
'Merengue',
'Méringue',
'Norteña',
'Ranchera',
'Salsa',
'Son',
'Tejano',
'Timba',
'Axé',
'Bossa Nova',
'Brazilian rock',
'Brega',
'Choro',
'Forró',
'Frevo',
'Funk Carioca',
'Lambada',
'Maracatu',
'Música popular brasileira',
'Música sertaneja',
'Pagode',
'Samba',
'Samba rock',
'Tecnobrega',
'Tropicalia',
'Zouk-Lambada'

];

var folk = [

'American folk revival',
'Anti-folk',
'British folk revival',
'Celtic music',
'Chalga',
'Contemporary folk',
'Filk music',
'Freak folk',
'Indie folk',
'Industrial folk',
'Neofolk',
'Progressive folk',
'Protest song',
'Psychedelic folk',
'Singer-songwriter movement',
'Skiffle',
'Sung poetry',
'Techno-folk',
'Cowboy',
'Western music'

];

var easy = [

'Background music',
'Beautiful music',
'Elevator music',
'Easy Listening',
'Furniture music',
'Lounge music',
'Middle of the road',
'New-age music'

];

var country = [

'Alternative country',
'Cowpunk',
'Blues country',
'Hokum',
'Outlaw country',
'Progressive country',
'Zydeco',
'Country rap',
'Red Dirt',
'Rockabilly',
'Hellbilly music',
'Psychobilly',
'Punkabilly',
'Country rock',
'Texas country',
'Americana',
'Australian country music',
'Bakersfield sound',
'Bluegrass',
'Progressive bluegrass',
'Reactionary bluegrass',
'Cajun',
'Cajun fiddle tunes',
'Christian country music',
'Classic country',
'Close harmony',
'Dansband music',
'Franco-country',
'Honky Tonk',
'Instrumental country',
'Nashville sound',
'Neotraditional country',
'Country pop',
'Sertanejo',
'Traditional country music',
'Truck-driving country',
'Western swing'

];

var electronic = [

'Ambient',
'Ambient dub',
'Ambient house',
'Ambient techno',
'Ambient industrial',
'Dark ambient',
'Space music',
'Drone music',
'Illbient',
'Psybient',
'Isolationism',
'Lowercase',
'Asian Underground',
'Breakbeat',
'Baltimore Club',
'Big beat',
'Breakbeat hardcore',
'Broken beat',
'Florida breaks',
'Nu skool breaks',
'4-beat',
'Chiptune',
'Bitpop',
'Game Boy music',
'Nintendocore',
'Video game music',
'Yorkshire Bleeps and Bass',
'Disco',
'Cosmic disco',
'Disco polo',
'Europop',
'Euro disco',
'Space disco',
'Italo disco',
'Nu-disco',
'Downtempo',
'Acid jazz',
'Balearic Beat',
'Chill out',
'Dub music',
'Dubtronica',
'Ethnic electronica',
'Moombahton',
'New-age music',
'Nu jazz',
'Trip hop',
'Drum and bass',
'Darkcore',
'Darkstep',
'Drumfunk',
'Drumstep',
'Hardstep',
'Intelligent drum and bass',
'Jump-Up',
'Liquid funk',
'Neurofunk',
'Oldschool jungle',
'Darkside jungle',
'Ragga-jungle',
'Raggacore',
'Sambass',
'Techstep',
'Electro',
'Crunk',
'Electro backbeat',
'Electro-grime',
'Electro swing',
'Electroacoustic',
'Acousmatic music',
'Computer music',
'Electroacoustic improvisation',
'Field recording',
'Live electronics',
'Live coding',
'Musique concrète',
'Soundscape composition',
'Tape music',
'Electronica',
'Berlin school',
'Chillwave',
'Electronic art music',
'Electronic dance music',
'Folktronica',
'Freestyle music',
'IDM',
'Glitch',
'Laptronica',
'Skweee',
'Sound art',
'Synthcore',
'Electronic rock',
'Alternative dance',
'Baggy',
'Madchester',
'Dance-punk',
'Dance-rock',
'Dark Wave',
'Electroclash',
'Electronicore',
'Electropunk',
'Ethereal wave',
'Indietronica',
'New rave',
'Space rock',
'Synthpop',
'Eurodance',
'Bubblegum dance',
'Italo dance',
'Turbofolk',
'Hardcore',
'Hard dance',
'Bouncy house',
'Bouncy techno',
'Breakcore',
'Darkcore',
'Digital hardcore',
'Doomcore',
'Dubstyle',
'Gabber',
'Happy hardcore',
'Hardstyle',
'Jumpstyle',
'Makina',
'Speedcore',
'UK hardcore',
'Hi-NRG',
'Eurobeat',
'Hard NRG',
'New Beat',
'House',
'Acid house',
'Chicago house',
'Deep house',
'Diva house',
'Dutch house',
'Electro house',
'French house',
'Funky house',
'Future house',
'Ghetto house',
'Hardbag',
'Hip house',
'Italo house',
'Latin house',
'Minimal house',
'Microhouse',
'Progressive house',
'Rave music',
'Tech house',
'Tribal house',
'UK hard house',
'US garage',
'Vocal house',
'Industrial',
'Aggrotech',
'Coldwave',
'Cybergrind',
'Dark electro',
'Death industrial',
'Electronic body music',
'Futurepop',
'Electro-industrial',
'Industrial metal',
'Neue Deutsche Härte',
'Industrial rock',
'Noise',
'Japanoise',
'Power noise',
'Power electronics',
'Witch House',
'Drag',
'Post-disco',
'Boogie',
'Dance-pop',
'Electropop',
'Progressive',
'Techno',
'Acid techno',
'Detroit techno',
'Free tekno',
'Ghettotech',
'Minimal',
'Nortec',
'Tecno brega',
'Techno-DNB',
'Toytown Techno',
'Trance',
'Acid trance',
'Classic trance',
'Dream trance',
'Goa trance',
'Psychedelic trance',
'Dark psytrance',
'Full on',
'Psyprog',
'Psybreaks',
'Suomisaundi',
'Hard trance',
'Tech trance',
'Uplifting trance',
'Orchestral Uplifting',
'Vocal trance',
'UK garage',
'2-step',
'Bassline',
'Breakstep',
'Dubstep',
'Trap',
'Funky',
'Grime',
'Speed garage',
'Future Bass'

];

var art = [

'Ballade',
'Canzona',
'Carol',
'Chanson',
'Fantasia',
'Chromatic fantasia',
'Galliard',
'Intermedio',
'Laude',
'Litany',
'Madrigal',
'Madrigal comedy',
'Madrigale spirituale',
'Mass',
'Cyclic mass',
'Parody mass',
'Paraphrase mass',
'Cantus firmus mass',
'Motet',
'Motet-chanson',
'Opera',
'Pavane',
'Ricercar',
'Sequence',
'Tiento',
'Toccata',
'Allemande',
'Canon',
'Cantata',
'Chaconne',
'Concerto',
'Concerto grosso',
'Solo concerto',
'Courante',
'Fugue',
'Gavotte',
'Gigue',
'Mass',
'Minuet',
'Opera',
'Opera buffa',
'Opera seria',
'Oratorio',
'Partita',
'Passacaglia',
'Prelude',
'Sarabande',
'Sinfonia',
'Sonata',
'Flute sonata',
'Trio sonata',
'Suite',
'Bagatelle',
'Ballade',
'Ballet',
'Classical ballet',
'Carol',
'Concerto',
'Cello concerto',
'Clarinet concerto',
'Double bass concerto',
'Flute concerto',
'Oboe concerto',
'Piano concerto',
'Trumpet concerto',
'Viola concerto',
'Violin concerto',
'Dance',
'Étude',
'Impromptu',
'Intermezzo',
'Mass',
'Mazurka',
'March',
'Music hall',
'Nocturne',
'Opera',
'Ballad opera',
'Opera buffa',
'Opéra comique',
'Opera seria',
'Operetta',
'Overture',
'Concert overture',
'Symphonic poem',
'Singspiel',
'Zarzuela',
'Concert Aria',
'Oratorio',
'Polonaise',
'Prelude',
'Quartet',
'Piano quartet',
'String quartet',
'Oboe quartet',
'Quintet',
'Piano quintet',
'String quintet',
'Requiem',
'Rhapsody',
'Rondo',
'Scherzo',
'Serenade',
'Sinfonia concertante',
'Sonata',
'Piano sonata',
'Violin sonata',
'Viola sonata',
'Cello sonata',
'Flute sonata',
'Clarinet sonata',
'Bassoon sonata',
'Symphony',
'Program symphony',
'Choral symphony',
'Suite',
'Waltz',
'Ballet',
'Neoclassical ballet',
'Contemporary ballet',
'Blues',
'Burlesque',
'Cabaret',
'Concerto for Orchestra',
'Modern dance',
'Moment form',
'Minimal music',
'Musical theatre',
'Opera',
'Popular song',
'Protest song',
'Soundtrack',
'Vaudeville',
'Video game music'

];

var genres = [hiphop, jazz, pop, rock, soul, latin, folk, easy, country, electronic, art];

/*
	-----------------------------------
	ARRAY FOR BUTTON TEXT
	-----------------------------------
*/

var words = [

	'DISCOVER SOMETHING NEW',
	'GIMME MOAR',
	'LET\'S TRY AGAIN',
	'MOAR PLZ',
	'ONE MORE TIME',
	'GET MUSIC',
	'SURPRISE ME',
	'RANDOM SONG',
	'KEEP TRYING',
	'DO IT AGAIN',
	'SOMETHING ELSE?'
];

/*
	-----------------------------------
	GRADIENT COLOR OBJECTS
	-----------------------------------
*/


var color = {
	start: '#16BFFD',
	end: '#CB3066'
};

var kyoto = {
	start: '#360033',
	end : '#0b8793'
};

/*
	-----------------------------------
	ARRAY FOR BACKGROUND GRADIENTS
	-----------------------------------
*/

var colors = [color, kyoto];